### PR TITLE
IOP is delivering wrong license link

### PR DESCRIPTION
**Pull request by patrickda**
IOP Article is licensed under a CC-BY 3.0 license

### CODE REVIEW

**Comment by cbroschinski** [comment]
Correction accepted, but note that the licence_ref field is automatically imported from CrossRef. If the link is wrong indeed, somebody should ask the people at IOP if they plan on [correcting their metadata](https://support.crossref.org/hc/en-us/articles/214298886-License-URIs-Technical-Details). In that case we could easily pull in the corrected URIs for all IOP articles in one sweep.

**Comment by ioverka** [comment]
Really? The License information at CrossRef looks fine to me:

http://api.crossref.org/works/10.1088/1367-2630/18/9/093042

The lookup probably should check the "content-version" element before considering the license URL, see https://github.com/CrossRef/rest-api-doc/blob/master/funder_kpi_metadata_best_practice.md#different-licenses-for-different-versions-of-the-content

**Comment by cbroschinski** [comment]
Oh, that's interesting. I did not consider that more than one license element might be in play. Will have a look at this. (BTW: ioverka = Inga from MPDL?)

**Comment by ioverka** [comment]
Genau... immer am neugierigen Herumspionieren 👀

**Comment by cbroschinski** [comment]
#343 modifies the license enrichment: If more than one license_ref element is present in the CrossRef data, the attribute applies_to="vor" determines which one will be used. All license information has been updated accordingly. Thanks again to @ioverka for bringing this to our attention.

**Pull request merged**
